name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
    paths:
      - 'wrangler.toml'
      - 'worker/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    # 仓库里找不到 wrangler.toml 就直接跳过本 job
    if: ${{ hashFiles('wrangler.toml') != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Show Wrangler version
        run: wrangler --version

      - name: Deploy with wrangler
        run: wrangler deploy --config wrangler.toml
