name = "oliverfr-com"
main = "src/worker.ts"          # ← 入口脚本路径
compatibility_date = "2024-11-21"
account_id = "132140e50408eb97542b782b829678b5"

# 如果你要走子域路由，可以加（可先不加）
# routes = [
#   { pattern = "api.oliverfr.com/*", zone_name = "oliverfr.com" }
# ]
