name: ci-core
     
on:
  pull_request:
    branches: [ "main", "release-*" ]
    paths-ignore: [ "dist/**", "**/*.snap" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - id: has_pkg
        run: |
          if [ -f package.json ]; then echo "yes=1" >> $GITHUB_OUTPUT; else echo "yes=0" >> $GITHUB_OUTPUT; fi

      - uses: actions/setup-node@v4
        if: steps.has_pkg.outputs.yes == '1'
        with: { node-version: 20, cache: 'npm' }

      - name: Install
        if: steps.has_pkg.outputs.yes == '1'
        run: npm ci

      - name: Run unit tests (Vitest)
        if: steps.has_pkg.outputs.yes == '1'
        run: |
          npm test -- --run || echo "::notice title=unit::No tests or script failed; skipping"
