name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    # 仓库里不存在 wrangler 配置时直接跳过这个 job
    if: ${{ hashFiles('wrangler.toml', 'wrangler.json') != '' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy with wrangler
        run: npx -y wrangler@4 deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
