name: Deploy to Cloudflare Workers
on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    # 没有 wrangler.toml 时直接跳过，避免“找不到入口”的红灯
    if: ${{ hashFiles('worker/wrangler.toml') != '' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 可选：调试时看看文件确实在
      - run: ls -la && cat wrangler.toml

      - name: Install wrangler@4
        run: npm i -g wrangler@4

      - name: Deploy worker
        run: wrangler deploy --config wrangler.toml
