name: Deploy to Cloudflare Workers
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm            # 依赖 package-lock.json 才会启用缓存

      - run: npm ci             # 用锁文件安装依赖

      - run: |
          if npm run | grep -q " build"; then npm run build; fi

      - run: npx wrangler deploy
