name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      PROJECT_NAME: your-pages-project-name   # 先在 Cloudflare Pages 创建项目
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # 如需构建，补充你的构建命令；否则去掉这步
      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy to Pages
        run: npx -y wrangler@4 pages deploy ./dist --project-name "$PROJECT_NAME"
