name: Deploy to Cloudflare Workers
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4

      # 只安装 Node，不启用任何缓存（不会检查 lockfile）
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 如无前端构建，这一步直接部署；也无需 npm ci
      - name: Deploy with wrangler
        run: npx -y wrangler@3 deploy
