name: Deploy to Cloudflare Workers
on:
  push:
    branches: [ main ]
    paths:                # 只有这些文件变化才跑部署
      - 'wrangler.toml'
      - 'worker/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 若仓库根不存在 wrangler.toml，就直接跳过（不失败）
      - id: has_wrangler
        run: |
          if [ -f wrangler.toml ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        if: steps.has_wrangler.outputs.present == 'true'
        with: { node-version: 20 }

      - name: Deploy with wrangler
        if: steps.has_wrangler.outputs.present == 'true'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx -y wrangler@4 deploy
