name: Deploy to Cloudflare Workers

on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 如果 wrangler.toml 在根目录，就不要 cd；保持默认工作目录 = 仓库根
      - name: Deploy with wrangler
        run: npx -y wrangler@3 deploy
