name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    # 仅 main 分支 且 仓库中存在 wrangler.toml 与 src/worker.js 时执行
    if: >
      github.ref == 'refs/heads/main' &&
      hashFiles('wrangler.toml') != '' &&
      hashFiles('src/worker.js') != ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files (debug)
        run: |
          pwd && ls -la
          test -f wrangler.toml && echo "wrangler.toml OK"
          test -f src/worker.js && echo "src/worker.js OK"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy with wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx -y wrangler@3 deploy
