name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
    paths:
      - 'wrangler.toml'
      - 'src/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    # 第二道保险，确保只会在 main 的 push 上真正执行
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Deploy with wrangler
        run: npx -y wrangler@4 deploy
