name: Quality Gates

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke-and-lighthouse:
    runs-on: ubuntu-latest
    env:
      SITE_URL: ${{ secrets.SITE_URL }}        # 你的线上页面 URL（含 http/https）
      TTS_API_URL: ${{ secrets.TTS_API_URL }}  # 若你是放在 secrets，就用 secrets；放在 vars 则换成 vars.

    steps:
      - uses: actions/checkout@v4

      # 1) 前端页面健康检查（HTTP 200）
      - name: Smoke check - page is reachable
        run: |
          set -Eeuo pipefail
          echo "Checking $SITE_URL ..."
          code=$(curl -fsSL -o /dev/null -w "%{http_code}\n" "$SITE_URL")
          echo "HTTP $code"
          test "$code" = "200"

      # 2) （可选）后端 API 健康检查（存在就检查）
      - name: Smoke check - API reachable (optional)
        if: ${{ env.TTS_API_URL != '' }}
        run: |
          set -Eeuo pipefail
          echo "Checking $TTS_API_URL ..."
          code=$(curl -fsSL -o /dev/null -w "%{http_code}\n" "$TTS_API_URL")
          echo "HTTP $code"
          if [ "$code" != "200" ] && [ "$code" != "405" ] && [ "$code" != "404" ]; then
            echo "Unexpected status: $code"
            exit 1
          fi

      # 3) 写入 Lighthouse 配置到临时文件（避免 ENAMETOOLONG）
      - name: Prepare Lighthouse config
        run: |
          cat > /tmp/lhci.json <<'JSON'
          {
            "ci": {
              "collect": { "numberOfRuns": 1 },
              "assert": {
                "assertions": {
                  "categories:performance":   ["warn", {"minScore": 0.80}],
                  "categories:accessibility": ["warn", {"minScore": 0.90}],
                  "categories:best-practices":["warn", {"minScore": 0.90}],
                  "categories:seo":           ["warn", {"minScore": 0.80}]
                }
              }
            }
          }
          JSON
          echo "Wrote /tmp/lhci.json"
          ls -l /tmp/lhci.json

      # 4) Lighthouse 基线
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ env.SITE_URL }}
          configPath: /tmp/lhci.json
          uploadArtifacts: true
          temporaryPublicStorage: true
