name: Quality Gates

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke-and-lighthouse:
    runs-on: ubuntu-latest
    env:
      SITE_URL: ${{ secrets.SITE_URL }}       # 前端页面 URL（已在 Secrets）
      TTS_API_URL: ${{ vars.TTS_API_URL }}    # 可为空；为空则跳过 API 健康检查

    steps:
      - uses: actions/checkout@v4

      # 1) 前端页面健康检查（HTTP 200）
      - name: Smoke check - page is reachable
        run: |
          set -Eeuo pipefail
          echo "Checking $SITE_URL ..."
          code=$(curl -fsSL -o /dev/null -w "%{http_code}\n" "$SITE_URL")
          echo "$code"
          test "$code" = "200"

      # 2) （可选）后端 API 健康检查（存在就检查）
      - name: Smoke check - API reachable (optional)
        if: env.TTS_API_URL != ''
        run: |
          set -Eeuo pipefail
          echo "Checking $TTS_API_URL ..."
          code=$(curl -fsSL -o /dev/null -w "%{http_code}\n" "$TTS_API_URL")
          echo "$code"
          if [ "$code" != "200" ] && [ "$code" != "405" ] && [ "$code" != "404" ]; then
            echo "Unexpected status: $code"
            exit 1
          fi

      # 3) 写入 LHCI 配置文件（阈值在此）
      - name: Write LHCI config to file
        run: |
          cat > lighthouserc.json <<'JSON'
          {
            "ci": {
              "collect": { "numberOfRuns": 1 },
              "assert": {
                "assertions": {
                  "categories:performance":   ["warn", { "minScore": 0.80 }],
                  "categories:accessibility": ["warn", { "minScore": 0.90 }],
                  "categories:best-practices":["warn", { "minScore": 0.90 }],
                  "categories:seo":           ["warn", { "minScore": 0.80 }]
                }
              }
            }
          }
          JSON

      # 4) 跑 Lighthouse（用文件路径，而非内联 JSON）
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: lighthouserc.json
          urls: |
            ${{ env.SITE_URL }}
          uploadArtifacts: true
          temporaryPublicStorage: true
