name: security-semgrep
   
on:
  pull_request:
    branches: [ "main", "release-*" ]
    paths-ignore: [ "dist/**", "**/*.snap" ]

permissions:
  security-events: write
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      # 使用官方 action 的安全默认：p/ci + 生成 SARIF
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: true

      # SARIF 可能因无规则匹配未生成；用 hashFiles 判断并跳过上传
      - name: Upload SARIF to code scanning
        if: ${{ hashFiles('semgrep.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
