name: semgrep-code-scanning

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write   # 允许上传到 Code Scanning

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: true
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: false
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: Semgrep
