name: unit-style

on:
  pull_request:
    branches: [ "main", "release-*" ]
    paths-ignore: [ "dist/**", "**/*.snap" ]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: ESLint
        run: npm run -s lint || true
      - name: Prettier check
        run: npm run -s fmt:check || npx prettier -c . || true
